### ISSUE TITLE
Compiler log file generation

### ISSUE THREAD

**Issue by taalas** [Bertk/cpptesting#1]
Hi,
I am currently trying to integrate you project structure into one of our projects to import SCA results into SonarQube. The basic structure seems to run fine for me, cppcheck is generating output (although it seems only to report not being able to read certain headers because it interprets them as C instead of C++).

You set a name for the compiler log file, how do you generate this file though? I wasn't successful in adding options to write this file in my TFS build agent task.

**Comment by Bertk** [comment]
Hi,
I updated the [Wiki ](https://github.com/Bertk/cpptesting/wiki/CppTesting-CI-configuration) and added configuration details.
The log file is created by the TFS agent and the name is should be `<SQCompilerLog>$(SolutionDir)$(SolutionFileName).log</SQCompilerLog>`. Please revisit the updated [SonarQube.StaticAnalysis.props](https://github.com/Bertk/cpptesting/blob/master/_Globals/BuildProps/SonarQube.StaticAnalysis.props) file.

**Comment by taalas** [comment]
Hi,
thanks for taking the time to answer!
I have updated the project structure to reflect your latest changes and also changed my build tasks to reflect your screenshots.
I still could not get compiler warnings to appear in SonarQube. Looking at my build server worker directory it seems that no log file is generated by the build task, even with the updated configuration.
My cppcheck does generate a file which is imported into SonarQube, the strange thing here is, that cppcheck behaves differently when called by the agent. Almost no warnings are generated. If I call cppcheck on the build agent directly with --enable=all I do get a lot of warnings. I have no clue what the difference might be, I enabled verbose mode for cppcheck and the run looks totally fine in the TFS log...except that it does not generate the warnings I see when I start it manually. This might be out of the scope of this issue, but have you experienced anything like this?

**Comment by Bertk** [comment]
Hi,
we use CppCheck and VC++ compiler warnings since some years and the reported warnings from both reports are available in the SQ database.
The log file should be available in the source folder
```
C:\agent\_work>dir /s /B *.log
C:\agent\_work\1\.sonarqube\out\ProjectInfo.log
C:\agent\_work\1\s\CppTesting.sln.log
```
and with the regular expression `^\x20+(.*)\((\d+)\)\x20*:\x20warning\x20(C\d+):\x20(.*)\x20\[C:\\agent\\_work\\1\\s\\Source\\RootFinder\\RootFinder.vcxproj\]$`

the 2 warning messages are detected:
```
Build started 11/18/2017 2:34:12 PM.
Project "C:\agent\_work\1\s\CppTesting.sln" on node 1 (default targets).
Building with tools version "15.0".
Target "ValidateSolutionConfiguration" in file "C:\agent\_work\1\s\CppTesting.sln.metaproj" from project "C:\agent\_work\1\s\CppTesting.sln" (entry point):
Task "Error" skipped, due to false condition; (('$(CurrentSolutionConfigurationContents)' == '') and ('$(SkipInvalidConfigurations)' != 'true')) was evaluated as (('<SolutionConfiguration>
...

"C:\agent\_work\1\s\CppTesting.sln" (default target) (1) ->
"C:\agent\_work\1\s\Source\RootFinder\RootFinder.vcxproj" (default target) (2) ->
(ClCompile target) -> 
  c:\agent\_work\1\s\source\rootfinder\dllmain.cpp(7): warning C4100: 'lpReserved': unreferenced formal parameter [C:\agent\_work\1\s\Source\RootFinder\RootFinder.vcxproj]
  c:\agent\_work\1\s\source\rootfinder\dllmain.cpp(4): warning C4100: 'hModule': unreferenced formal parameter [C:\agent\_work\1\s\Source\RootFinder\RootFinder.vcxproj]

```
Did you activate the rules for VC-compiler in the assigned or default **Quality Profile**?

![image](https://user-images.githubusercontent.com/2315215/33267458-dc5c6c92-d379-11e7-9b54-3ae58d4a151b.png)

**Comment by taalas** [comment]
Hi!
There has to be something wrong with my agent's access rights on the build client. After a successful run I don't have any logfiles residing in my project directory. There is an msbuild.log in _work\_tasks\VSBuild_{id}\... though. I have to check what is going on...
The rules are activated for my quality profile, since I don't have a log file though, the Sonar sensor for logfiles does not find any files and thus does not apply the RegExp at all.
My cppcheck runs fine and generates a file, the strange thing with this is just that it does not generate enough warnings (having checked manually) despite the fact that the call seems to be identical...very strange...

**Comment by Bertk** [comment]
Hi, 

I hope you solved your issue with the VNext build. I close this issue for the cpp-testing demo project.

Best regards
Bert
